<?php
    // \Closure -> fonction anonyme
    // use : permet d'envoyer dans la \Closure un paramètre sans avoir à le transmet à chacun des appels de la fonction
    $getErrors = function(string $key) use ($errors): string {
        $html = "";
        if(array_key_exists($key, $errors)) {
            // $html = $html . '<div class="invalid-feedback">';
            $html .= '<div class="invalid-feedback">';
            foreach($errors[$key] as $message) {
                $html .= $message . "<br />";
            } 
            $html .= "</div>";
        }

        return $html;
    };
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire Adresse</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container-fluid">
        <header class="pt-5">
            <h1>Formulaire Adresse</h1>
            <hr />
        </header>
        <main>
            <form method="post" action="">
                <div class="mb-3">
                    <label>Rue</label>
                    <input type="text" class="form-control <?php echo array_key_exists("street", $errors) ? "is-invalid": null ?>" 
                        name="street" value="<?php echo $address->getStreet() ?>" />
                    <?php echo $getErrors('street'); ?>
                </div>
                <div class="mb-3">
                    <label>Code Postal</label>
                    <input type="text" class="form-control <?php echo array_key_exists("zipCode", $errors) ? "is-invalid": null ?>" 
                        name="zipCode" value="<?php echo $address->getZipCode() ?>" />
                    <?php echo $getErrors('zipCode'); ?>
                </div>
                <div class="mb-3">
                    <label>Ville</label>
                    <input type="text" class="form-control <?php echo array_key_exists("city", $errors) ? "is-invalid": null ?>" 
                        name="city" value="<?php echo $address->getCity() ?>" />
                    <?php echo $getErrors('city'); ?>
                </div>
                <div class="mb-3">
                    <label>Pays</label>
                    <input type="text" class="form-control" name="country" value="<?php echo $address->getCountry() ?>" />
                </div>
                <button class="btn btn-outline-primary">Enregistrer</button>
            </form>

            <?php if($_SERVER['REQUEST_METHOD'] == "POST" && empty($errors)): ?>
                <div class="border rounded p-3 mt-3 w-25">
                    <h3>Adresse</h3>
                    <?php echo App\Company\AddressFormatter\FrenchAddressFormatter::format($address); ?>
                </div>
            <?php endif; ?>
        </main>
    </div>
</body>
</html>