<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire Client</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container-fluid">
        <header class="pt-5">
            <h1>Formulaire Client</h1>
            <hr />
        </header>
        <main>
            <form method="post" action="">
                <div class="mb-3">
                    <label>Nom</label>
                    <input type="text" class="form-control <?php echo array_key_exists("lastname", $errors) ? "is-invalid": null ?>" 
                        name="lastname" value="<?php echo $client->getLastname() ?>" />
                    <?php if(array_key_exists("lastname", $errors)): ?>
                    <div class="invalid-feedback">
                    <?php foreach($errors['lastname'] as $message) {
                        echo $message.'<br />';
                    } ?>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="mb-3">
                    <label>Prénom</label>
                    <input type="text" class="form-control <?php echo array_key_exists("firstname", $errors) ? "is-invalid": null ?>" 
                        name="firstname" value="<?php echo $client->getFirstname() ?>" />
                    <?php if(array_key_exists("firstname", $errors)): ?>
                    <div class="invalid-feedback">
                    <?php foreach($errors['firstname'] as $message) {
                        echo $message.'<br />';
                    } ?>
                    </div>
                    <?php endif; ?>
                </div>
                <div class="mb-3">
                    <label>Email</label>
                    <input type="text" class="form-control" name="email" value="<?php echo $client->getEmail() ?>" />
                </div>
                <div class="mb-3">
                    <label>Téléphone</label>
                    <input type="text" class="form-control" name="phone" value="<?php echo $client->getPhone() ?>" placeholder="+33 0 12 34 56 78" />
                    <div class="form-text">
                        Veuillez saisir votre numéro en précisant l'indicateur du pays (ex: +33)
                    </div>
                </div>
                <div class="mb-3">
                    <label>Date de naissance</label>
                    <input type="date" class="form-control" name="birthday" 
                        value="<?php echo $client->getBirthday() ? $client->getBirthday()->format('Y-m-d') : null ?>" />
                </div>
                <button class="btn btn-outline-primary">Enregistrer</button>
            </form>

            <?php if($_SERVER['REQUEST_METHOD'] == "POST" && empty($errors)): ?>
            <dl>
                <dt>
                    <i class="bi bi-person-badge"></i> Client
                </dt>
                <dd>
                    <?php echo $client->getFullname() ?>
                </dd>
                <dt>
                    <i class="bi bi-envelope"></i> Email
                </dt>
                <dd>
                    <?php echo $client->getEmail() ?>
                </dd>
                <dt>
                    <i class="bi bi-telephone-fill"></i> Téléphone
                </dt>
                <dd>
                    <?php echo $client->getPhone() ?>
                </dd>
                <dt>
                    <i class="bi bi-calendar2-event"></i> 
                    Date de naissance
                </dt>
                <dd>
                    <?php echo $client->getBirthday()->format('Y-m-d') ?>
                </dd>
            </dl>
            <?php endif; ?>
        </main>
    </div>
</body>
</html>