<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Client</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container-fluid">
        <header class="pt-5">
            <h1>Client</h1>
            <hr />
        </header>
        <main>
            <div class="row">
                <div class="col">
                    <dl>
                        <dt>
                            <i class="bi bi-person-badge"></i> Client
                        </dt>
                        <dd>
                            <?php echo $customer->getFullname() ?>
                        </dd>
                        <dt>
                            <i class="bi bi-envelope"></i> Email
                        </dt>
                        <dd>
                            <?php echo $customer->getEmail() ?>
                        </dd>
                        <dt>
                            <i class="bi bi-telephone-fill"></i> Téléphone
                        </dt>
                        <dd>
                            <?php echo $customer->getPhone() ?>
                        </dd>
                        <dt>
                            <i class="bi bi-calendar2-event"></i> 
                            Date de naissance
                        </dt>
                        <dd>
                            <?php echo formatDate($customer->getBirthday()) ?>
                        </dd>
                        <?php if( $customer->getAddress() != null ): ?>
                        <dt>
                            <i class="bi bi-houses-fill"></i> Adresse
                        </dt>
                        <dd>
                            <?php echo App\Company\AddressFormatter\USAddressFormatter::format($customer->getAddress()); ?>
                        </dd>
                        <?php endif; ?>
                    </dl>
                </div>
                <div class="col">
                    <h2 class="h5">Commandes</h2>
                    <table class="table">
                    <?php foreach($customer->getOrders() as $order): ?>
                        <tr>
                            <td><?php echo $order->getReference() ?></td>
                            <td><?php echo formatDate($order->getDate()) ?></td>
                            <td><?php echo currency($order->getTotalHT()) ?></td>
                            <td><?php echo currency($order->getTotalTTC()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </main>
    </div>
</body>
</html>